# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: eyes/base
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: NodePort
  port: 8000
