version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.7
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/*"
    platform: linux/amd64
    volumes:
      - ..:/workspace:cached
    networks:
      - eyes
    command: sleep infinity

  mysql:
    image: mysql:8
    platform: linux/amd64
    volumes:
      - eyes-mysql:/var/lib/mysql
    env_file: ../.env
    ports:
      - 3306:3306
    networks:
      - eyes

  redis:
    image: redis:latest
    volumes:
      - eyes-redis:/data
    ports:
      - 6379:6379
    networks:
      - eyes

volumes:
  eyes-mysql:
  eyes-redis:

networks:
  eyes:
