tasks:
  batch_size: 1000
wiki:
  categories:
    - type: PERSON
      urls:
        - https://zh.wikipedia.org/wiki/Category:%E5%8F%B0%E7%81%A3%E9%9B%BB%E8%A6%96%E5%A5%B3%E6%BC%94%E5%93%A1
        - https://zh.wikipedia.org/wiki/Category:%E8%87%BA%E7%81%A3%E9%9B%BB%E8%A6%96%E7%94%B7%E6%BC%94%E5%93%A1
        - https://zh.wikipedia.org/wiki/Category:%E5%8F%B0%E7%81%A3%E5%A5%B3%E6%AD%8C%E6%89%8B
        - https://zh.wikipedia.org/wiki/Category:%E5%8F%B0%E7%81%A3%E7%94%B7%E6%AD%8C%E6%89%8B
        - https://zh.wikipedia.org/wiki/Category:%E9%A6%AC%E4%BE%86%E8%A5%BF%E4%BA%9E%E8%8F%AF%E8%AA%9E%E6%B5%81%E8%A1%8C%E9%9F%B3%E6%A8%82%E6%AD%8C%E6%89%8B
        - https://zh.wikipedia.org/wiki/Category:%E6%96%B0%E5%8A%A0%E5%9D%A1%E5%A5%B3%E6%AD%8C%E6%89%8B
        - https://zh.wikipedia.org/wiki/Category:%E6%BE%B3%E5%A4%A7%E5%88%A9%E4%BA%9E%E5%A5%B3%E6%AD%8C%E6%89%8B
        - https://zh.wikipedia.org/wiki/Category:%E6%97%A5%E6%9C%AC%E5%A5%B3%E6%AD%8C%E6%89%8B
        - https://zh.wikipedia.org/zh-tw/Category:%E6%97%A5%E6%9C%AC%E7%94%B7%E6%AD%8C%E6%89%8B
        - https://zh.wikipedia.org/wiki/Category:%E6%97%A5%E6%9C%AC%E6%A8%82%E5%9C%98
        - https://zh.wikipedia.org/wiki/Category:%E8%87%BA%E7%81%A3%E7%94%B7%E6%80%A7%E6%94%BF%E6%B2%BB%E4%BA%BA%E7%89%A9
        - https://zh.wikipedia.org/wiki/Category:%E8%87%BA%E7%81%A3%E7%94%B7%E6%80%A7%E7%AB%8B%E6%B3%95%E5%A7%94%E5%93%A1
        - https://zh.wikipedia.org/wiki/Category:%E5%8F%B0%E5%8C%97%E5%B8%82%E5%B8%82%E9%95%B7
        - https://zh.wikipedia.org/wiki/Category:%E8%87%BA%E7%81%A3%E5%A5%B3%E6%80%A7%E6%94%BF%E6%B2%BB%E4%BA%BA%E7%89%A9
        - https://zh.wikipedia.org/wiki/Category:%E6%B0%91%E4%B8%BB%E9%80%B2%E6%AD%A5%E9%BB%A8%E5%A5%B3%E9%BB%A8%E5%93%A1
        - https://zh.wikipedia.org/wiki/Category:%E4%B8%AD%E5%9C%8B%E5%9C%8B%E6%B0%91%E9%BB%A8%E5%A5%B3%E9%BB%A8%E5%93%A1
        - https://zh.wikipedia.org/wiki/Category:%E4%B8%AD%E5%9C%8B%E5%9C%8B%E6%B0%91%E9%BB%A8%E9%BB%A8%E5%93%A1
        - https://zh.wikipedia.org/wiki/Category:%E6%B0%91%E4%B8%BB%E9%80%B2%E6%AD%A5%E9%BB%A8%E9%BB%A8%E5%93%A1
        - https://zh.wikipedia.org/wiki/Category:%E8%87%BA%E7%81%A3%E5%A5%B3%E6%80%A7YouTuber
        - https://zh.wikipedia.org/wiki/Category:%E8%87%BA%E7%81%A3%E5%9C%98%E9%AB%94YouTuber
        - https://zh.wikipedia.org/wiki/Category:%E8%87%BA%E7%81%A3%E7%94%B7%E6%80%A7YouTuber