apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
    spec:
      containers:
        - name: "{{ .Release.Name }}"
          image: '{{ .Values.image }}:{{ .Values.tag | default "default" }}'
          command: ["/bin/bash", "-c", "--"]
          args:
            [
              "poetry run celery -A eyes.celery worker --concurrency={{ .Values.celery.concurrency }}",
            ]
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: eyes-config-prod
