name: checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Pre-commit checks
        run: |
          poetry run pre-commit run --all-files
